config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pasta_types, only: [:index, :show]
  resources :formules, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/formule.rb
class Formule < ApplicationRecord
  has_many :users
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :formule
  has_many :pasta_orders
  has_many :pasta_types, through: :pasta_orders

  validates :status, inclusion: { in: ["to prepare", "in progress", "ready", "sent", "cancelled"]}

# list the orders by their status

  def self.to_prepare
    Order.where(status: "to prepare")
  end

  def self.in_progress
    Order.where(status: "in progress")
  end

  def self.ready
    Order.where(status: "ready")
  end

  def self.sent
    Order.where(status: "sent")
  end

  def self.cancelled
    Order.where(status: "cancelled")
  end

# methodes de changement de status

  def prepare!
    self.status = "in progress"
    save!
  end

  def ready!
    self.status = "ready"
    save!
  end

  def send!
    self.status = "sent"
    save!
  end

  def cancel!
    self.status = "cancelled"
    save!
  end

end

app/models/pasta_order.rb
class PastaOrder < ApplicationRecord
  belongs_to :pasta_type
  belongs_to :order
end

app/models/pasta_type.rb
class PastaType < ApplicationRecord
  has_many :pasta_orders
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :formule, optional: true
  has_many :orders

  validates :email, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :phone_number, format: { with: /0[0-9]{9}/, message: "Invalid format, we need 10 digitsstarting with 0" }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def unsubscribe!
    self.formule = Formule.find_by(price: 0) #permettra de dissocuer les user qui n'ont jamais été abonnés (formule_id: nil) de ceux qui ce sont désabonnés (formule_id: 1)
    save!
  end

  def formule_1
    self.formule = Formule.find_by(price: 15)
    save!
  end

  def formule_2
    self.formule = Formule.find_by(price: 25)
    save!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :phone_number])

      # For additional in app/views/devise/registrations/edit.html.erb
      # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end

end

app/controllers/formules_controller.rb
class FormulesController < ApplicationController

  def index
    @formules = Formule.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/pasta_types_controller.rb
class PastaTypesController < ApplicationController
  def index         # GET /restaurants
    @pasta_types = PastaType.all
  end

  # def show          # GET /restaurants/:id
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/formules/index.html.erb
<div class="container">
  <div class="row">
    <h1>Formules</h1>
    <div class="col-sm-6 col-md-6">
      <h3>Formule 1 - Pasta enthusiast</h3>
      <p><%#= formule_1.packs %> packs of pasta every week for only <%#= formule_1.price %> euros per month</p>
    </div>
    <div class="col-sm-6 col-md-6">
      <h3>Formule 2 - Pasta fanatic</h3>
      <p><%#= formule_2.packs %> packs of pasta every week for only <%#= formule_2.price %> euros per month</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pasta Fresca Box | The pleasure to eat pasta every week |</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- TODO

OK A public accessible home page

OK with a form to allowed users to register (name, email, city, phone_number, password)

Each field must be validated in order to have data as accurate as possible. -->

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url('https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=707dd400ff0bb8d6b10e42397f7e275a&auto=format&fit=crop&w=1350&q=80');">
  <div class="banner-content">
    <h1>Pasta Fresca Box</h1>
    <p>The pleasure to eat pasta every weeks.</p>
    <a href="/pasta_types" class="btn btn-primary btn-lg">Start now</a>
  </div>
</div>

app/views/pasta_types/index.html.erb
<div class="container">
  <h2 class="h2-past-type">Available Pasta, just for you!</h2>
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://static.cuisineaz.com/610x610/i9837-gnocchi-di-patate.jpg');">
        <div class="card-description">
          <h2>Gnocci</h2>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://cdn.shopify.com/s/files/1/1935/9089/products/rustichella-dabruzzo-orecchiette-product-shot-1000x1000_530x@2x.jpg?v=1523665518');">
        <div class="card-description">
          <h2>Orecchiette</h2>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://static3.depositphotos.com/1000789/120/i/950/depositphotos_1208604-stock-photo-pasta-fusili-as-background.jpg');">
        <div class="card-description">
          <h2>Fusili</h2>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://static.pratico-pratiques.com/uploads/images/recipe_express/orig/c06248832d33b84d1ed86225e06968fb/pennes-sauce-cremeuse-au-parmesan-et-courge-butternut.jpeg');">
        <div class="card-description">
          <h2>Penne</h2>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://st.depositphotos.com/1011845/2049/i/950/depositphotos_20497449-stock-photo-pasta-tortiglioni.jpg');">
        <div class="card-description">
          <h2>Tortiglioni</h2>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://454a3915j1d326y4rhle8lk1-wpengine.netdna-ssl.com/wp-content/uploads/2017/10/Spaghettisalacarbonaradethon-1000x500.jpg');">
        <div class="card-description">
          <h2>Spaghetti</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center btn-to-formule">
    <%= link_to "Choose my formule", formules_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Our catalog", pasta_types_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Our formules", formules_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>      <%= link_to "Our catalog", pasta_types_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Our formules", formules_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>